### PR TITLE
fix: error message formats for size_t parameters

### LINKED ISSUE #59: Incorrect format specifier usage.
There is a bunch of places with code like 
`sexp_error(sexp_exception_t::error, "Declared length was %d, but quoted string ended too early", (int) length, 0, count);`.
Later it goes to snprintf, however it would use type size_t for c1 and c2 (`%zu`), not the `%d` like it is specified in the format string. Also (int) length doesn't make sense here as parameter would be converted to size_t.

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

File: src/sexp-error.cpp [hunk 1]
```diff
@@ -39,18 +39,31 @@ std::string sexp_exception_t::format(std::string prf,
...
+
+void sexp_error(
+  sexp_exception_t::severity level, const char *msg, size_t c1, size_t c2, int pos)
+{
+    char tmp[256];
+    snprintf(tmp, sizeof(tmp) / sizeof(tmp[0]), msg, c1, c2);
+    sexp_error(level, tmp, pos);
+}
+
 } // namespace sexp
```
Comment (ni4) [inline src/sexp-error.cpp]: No EOL at the file end?

**Review by ni4 — APPROVED** [review]
LGTM, just one missing eol on file end. Thanks!

File: src/sexp-error.cpp (hunk 1 above)
Comment (maxirmx) [reply src/sexp-error.cpp]: Thank you, fixed
